//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using Core.Contracts.Entities;
    using System;
    using System.Collections.Generic;

    public partial class ParkArea : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkArea()
        {
            this.ParkAreaWithOwners = new HashSet<ParkAreaWithOwner>();
            this.Pricings = new HashSet<Pricing>();
        }

        public int Id { get; set; }
        public string ParkName { get; set; }
        public int MaxCount { get; set; }
        public int CurrentCount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public string Address { get; set; }
        public string Coordinate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Status { get; set; }

        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkAreaWithOwner> ParkAreaWithOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pricing> Pricings { get; set; }
    }
}
